### PR TITLE
Update pve2_api.class.php

### PR DESCRIPTION
**Pull request by naja7host**
add port as var .

### CODE REVIEW

**Comment by danhunsaker** [comment]
In future, please name your commits and pull requests with the functionality that was changed, rather than the file.  The file(s) changed are already available in the commit itself, and it's impossible to tell what a given PR is for when it just names a changed file.

**Comment by danhunsaker** [comment]
That said, this change breaks backward compatibility pretty hard.  Add the port as a final, optional argument, not in the middle of the argument list.  Perhaps better, don't change the arguments at all, and simply handle the argument contents a bit more intelligently: pass `'proxmox.example.com:8080'` instead of `'proxmox.example.com', 8080`.  You can do `list($this->hostname, $this->port) = explode(':', $hostname);`, though be sure to put the default (`8006`) into `$this->port` if it's empty afterward.  That gives you the control you need, doesn't break backwards compatibility, and happens to be a bit cleaner to implement.

(I also regularly complain about developers who use `"https://" . $this->hostname . ":" . $this->port . "/...` instead of `"https://{$this->hostname}:{$this->port}/...`, but that's more of a personal preference than anything practical, and I'm not even close to pointing fingers at you for it, since it's in the original unpatched code that way.)

**Comment by naja7host** [comment]
yuou can do it as you see is better for all . i don't ask to use my code, but just to ipmlement this update , just to make the port as a var , this way we can controll the port from our own script , rather than change it manually in the class . 

what do you think ?

**Comment by danhunsaker** [comment]
Just some feedback.  It's a good change, it just needs some tweaking to the implementation.

**Comment by CpuID** [comment]
I agree with @danhunsaker on this one, an optional final argument for port instead of breaking compatibility. Default value on the optional being the currently used port 8006.

Personally I like the idea of separating the port argument as opposed to appending it to the hostname, feels nicer compatibility wise and more explicit.

**Comment by CpuID** [comment]
Functionality added in eb0ece3e686266084ef4df4443370c34521e48d6

**Comment by naja7host** [comment]
thanks for this addition .

**Pull request closed without merging**
